[package]
name = "convcodes"
version = "0.1.0"
edition = "2024"

[dependencies]
awgn = { git = "ssh://git@github.com/garbagetrash/awgn.git" }

[[bin]]
name = "ccsds_rate_1_2_ber_curve"

[[bin]]
name = "constraint_3"
